qword/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'


urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),
]

qword/qword/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'homepage'

urlpatterns = [
    path('', include('homepage.urls'), name='homepage'),
    path('words/', include('words.urls'), name='words'),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

qword/words/urls.py
from django.urls import path

from . import views

app_name = 'words'


urlpatterns = [
    path('',  views.WordListView.as_view(), name='list'),
    path('add/',  views.words_add, name='add'),
    path('<int:pk>/delete/',  views.words_delete, name='delete'),
]

qword/words/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Word(models.Model):
    """Модель для слов."""
    id = models.AutoField(
        primary_key=True
    )
    word = models.CharField(
        max_length=30,
        verbose_name='Слово',
        db_index=True,
        blank=False
    )
    translate = models.CharField(
        max_length=30,
        verbose_name='Перевод',
        blank=False
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        """Дополнительная информация о модели Word."""
        ordering = ('created_at',)
        unique_together = ('word', 'translate',)
        verbose_name = 'слово'
        verbose_name_plural = 'слова'

    def __str__(self):
        """Возвращает все поля подписки."""
        return (
            f'{self.word} — {self.translate}'
        )

qword/words/forms.py
from django import forms

from .models import Word


class WordForm(forms.ModelForm):
    word = forms.CharField(
        max_length=30,
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'СЛОВО'})
    )
    translate = forms.CharField(
        max_length=30,
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'ПЕРЕВОД'})
    )

    class Meta:
        model = Word
        fields = ('word', 'translate',)

qword/homepage/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    """Начальная страница."""
    template_name = 'homepage/index.html'


class AboutPage(TemplateView):
    """Информационная страница."""
    template_name = 'homepage/about.html'

qword/words/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, ListView

from .forms import WordForm
from .models import Word


class WordListView(ListView):
    """Выводит список слов из БД."""
    model = Word
    template_name = 'words/word_list.html'


class WordCreateView(CreateView):
    """Добавляет слово в БД."""
    model = Word
    fields = ('word', 'translate')
    template_name = 'words/word_add.html'
    form_class = WordForm

    def get_context_data(self, **kwargs):
        # TODO
        return  {
            'form': form
        }

    def form_valid(self, form):
        form.save()

    def get_success_url(self):
        return reverse('words:list')


def words_delete(request, pk):
    """Удаляет слово из БД."""
    get_object_or_404(Word, pk=pk).delete()
    return redirect('words:list')

qword/templates/base.html
{% load static %}

 <!DOCTYPE html>
 <html lang="ru">
   <head>
    <title>QWord</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/htmx.min.js' %}" ></script>
   </head>
   <body>
      {% include "includes/header.html" %}
     <main>
       {% block content %}Контента пока нет{% endblock %}
     </main>
      {% include "includes/footer.html" %}
   </body>
 </html>

qword/templates/homepage/about.html
{% extends "base.html" %}

{% block content %}
  <h1>
    О проекте
  </h1>
{% endblock %}

qword/templates/homepage/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Главная
  </h1>
{% endblock %}

qword/templates/includes/footer.html
<footer>
  <hr>
  <div class="footer">
    <p>QWord | 2024</p>
  </div>
</footer>

qword/templates/includes/header.html
<header>
  <div class="navbar">
    <p>
      <a class="header-logo" href="{% url 'homepage:homepage' %}">QWord</a>
    </p>
    <ul>
      <li>
        <a href="{% url 'homepage:homepage' %}">Главная</a>
      </li>
      <li>
        <a href="{% url 'homepage:about' %}">О проекте</a>
      </li>
      <li>
        <a href="{% url 'words:list' %}">Мой словарь</a>
      </li>
      <li>
        <a href="{% url 'words:add' %}">Добавить</a>
      </li>
    </ul>
  </div>
</header>
<hr>

qword/templates/words/word_add.html
{% extends "base.html" %}

{% block content %}
<div class="word-add-container">
  <form method="post">
    {% csrf_token %}
    {{ form }} 
    <input class="word-add" type="submit" value="+">
  </form>
</div>
{% endblock %}

qword/templates/words/word_list.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }}</h1> 
    <table>
      <tr>
      <th>СЛОВО</th>
      <th>ПЕРЕВОД</th>
      <th style="width: 30px;"></th>
      </tr>
      {% for word in object_list %}
        <tr>
          <th>{{ word.word }}</th>
          <th>{{ word.translate }}</th>
          <th style="width: 30px;">
             <form action="{% url 'words:delete' word.id %}">
              <input class="delete" type="submit" value="✖" />
            </form>
          </th>
        </tr>
      {% endfor %}
    </table>
{% endblock %}